//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыжонок.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_HealthProblem
    {
        public int Id { get; set; }
        public int Id_Emploee { get; set; }
        public int Id_HealthProblem { get; set; }
    
        public virtual Emploee Emploee { get; set; }
        public virtual HealthProblem HealthProblem { get; set; }
    }
}
