//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыжонок.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityHistory
    {
        public int Id { get; set; }
        public int Id_Agent { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Agent Agent { get; set; }


        public int CurrentPriority
        {
            get
            {

                return Priority;
            }
        }
    }
}
