//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыжонок.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Standard
    {
        public int Id { get; set; }
        public int Id_Product { get; set; }
        public int Id_Standard { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Standard Standard { get; set; }
    }
}
