//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыжонок.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MinimumPrice = new HashSet<MinimumPrice>();
            this.Product_Standard = new HashSet<Product_Standard>();
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_ProductType { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Id_Package { get; set; }
        public Nullable<double> Netto { get; set; }
        public Nullable<double> Brutto { get; set; }
        public string Sertificate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinimumPrice> MinimumPrice { get; set; }
        public virtual Package Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Standard> Product_Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
