//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыжонок.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_material
    {
        public int Id { get; set; }
        public int Id_Production { get; set; }
        public int Id_Material { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Production Production { get; set; }
    }
}
